/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMessageQueueReceiver,
  IMessageQueueReceiverInterface,
} from "../IMessageQueueReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sender",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
    ],
    name: "processVaraMessage",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMessageQueueReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IMessageQueueReceiverInterface {
    return new Interface(_abi) as IMessageQueueReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMessageQueueReceiver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMessageQueueReceiver;
  }
}
