/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMessageQueueReceiver__factory } from "./IMessageQueueReceiver__factory";
export { PingReceiver__factory } from "./PingReceiver__factory";
