/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMessageQueueReceiver } from "./IMessageQueueReceiver";
export type { PingReceiver } from "./PingReceiver";
export * as factories from "./factories";
export { IMessageQueueReceiver__factory } from "./factories/IMessageQueueReceiver__factory";
export { PingReceiver__factory } from "./factories/PingReceiver__factory";
