/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PingReceiverInterface extends Interface {
  getFunction(nameOrSignature: "processVaraMessage"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PongEmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "processVaraMessage",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "processVaraMessage",
    data: BytesLike
  ): Result;
}

export namespace PongEmittedEvent {
  export type InputTuple = [sender: BytesLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PingReceiver extends BaseContract {
  connect(runner?: ContractRunner | null): PingReceiver;
  waitForDeployment(): Promise<this>;

  interface: PingReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  processVaraMessage: TypedContractMethod<
    [sender: BytesLike, arg1: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "processVaraMessage"
  ): TypedContractMethod<
    [sender: BytesLike, arg1: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "PongEmitted"
  ): TypedContractEvent<
    PongEmittedEvent.InputTuple,
    PongEmittedEvent.OutputTuple,
    PongEmittedEvent.OutputObject
  >;

  filters: {
    "PongEmitted(bytes32)": TypedContractEvent<
      PongEmittedEvent.InputTuple,
      PongEmittedEvent.OutputTuple,
      PongEmittedEvent.OutputObject
    >;
    PongEmitted: TypedContractEvent<
      PongEmittedEvent.InputTuple,
      PongEmittedEvent.OutputTuple,
      PongEmittedEvent.OutputObject
    >;
  };
}
